/**
 * Cross-cutting types shared between backend and React Native app.
 * Keep this file dependency-free and runtime-free (types + trivial constants only).
 */

export type PuzzleKind = 'crossword' | 'cloze' | 'flashcards';

/**
 * Constant token used wherever a "term-shaped blank" appears in user-facing text.
 * Lives in `shared` so the LLM prompts (Person B), the cloze engine (Person A), and the
 * cloze screen (Person C) all agree on the exact string. Changing this is a contract
 * change across all three.
 */
export const MASK_TOKEN = '[MASK]';

/**
 * A note source uploaded or pasted by the user. The underlying storage row; you almost
 * always want `Space` (which adds the FSRS-driven summary) instead.
 */
export interface NotesFile {
  id: string;
  title: string;
  createdAt: string;
  byteLength: number;
}

/**
 * A persistent container seeded from a notes file. Owns the raw notes, the extracted
 * terms, the FSRS state for those terms, all puzzles generated from them, and the review
 * history. UI navigation is space-centric: `id === notesFileId`.
 */
export interface Space {
  id: string;
  title: string;
  createdAt: string;
  byteLength: number;
  summary: SpaceSummary;
}

/**
 * Aggregated stats for a `Space`. All counts derive from the store + FSRS state; nothing
 * here is user-set. Dates are ISO-8601 in the server's local timezone for the daily fields
 * (`dueToday`, `playedTodayKinds`, `streakDays`) since the backend has no client tz.
 */
export interface SpaceSummary {
  termCount: number;
  /** Terms currently due as of `now` (unreviewed terms count as due). */
  dueCount: number;
  /** Terms that have never been reviewed. */
  newCount: number;
  /** Terms with FSRS stability >= STABILITY_THRESHOLD_DAYS (the cloze router's threshold). */
  stableCount: number;
  /** ISO timestamp of the most recent review event for any term in this space. */
  lastReviewedAt?: string;
  /** Kind of the most recent ended session for this space. */
  lastPuzzleKind?: PuzzleKind;

  // NYT-style daily display fields (server local time).
  /** Terms due by end of today's local date (subset of `dueCount`-or-future). */
  dueToday: number;
  /** Puzzle kinds whose session finished within today's local date. */
  playedTodayKinds: PuzzleKind[];
  /** Consecutive past calendar days (including today) with >= 1 finished session. */
  streakDays: number;
}

/**
 * A term extracted from the user's notes. The masked answer in any puzzle is always a verified term.
 *
 * - `sourceSpan` is a literal substring of the source notes (anti-hallucination tier 1).
 * - `styleAnchor` is the original sentence the term appeared in. Every clue/cloze/coach prompt
 *   receives this as a "match this style" reference (source-mimicry register strategy).
 */
export interface Term {
  id: string;
  notesFileId: string;
  term: string;
  definition: string;
  sourceSpan: string;
  styleAnchor: string;
}

/**
 * FSRS-rated review of a single term within a session. 1=Again, 2=Hard, 3=Good, 4=Easy.
 */
export type Rating = 1 | 2 | 3 | 4;

export interface Review {
  termId: string;
  rating: Rating;
  ms: number;
  hintsUsed: number;
}

/**
 * Crossword puzzle payload returned by the backend.
 */
export interface CrosswordEntry {
  term: string;
  clue: string;
  termId: string;
  startX: number;
  startY: number;
  orientation: 'across' | 'down';
}

export interface CrosswordPuzzle {
  kind: 'crossword';
  id: string;
  /** Owning space; set so back-navigation works without consulting session state. */
  spaceId: string;
  width: number;
  height: number;
  entries: CrosswordEntry[];
}

/**
 * Cloze puzzle item. `mode` records whether the sentence came from the notes verbatim
 * or was generated by the LLM (with a grounding verifier check).
 *
 * `previousMode` is the mode this term was served with last session (if any). The app
 * uses the transition `anchored` → `generated` to render a "Regenerated for you" badge;
 * the backend stamps it from the most recent prior ClozeItem for this termId.
 */
export interface ClozeItem {
  termId: string;
  sentence: string;
  answer: string;
  mode: 'anchored' | 'generated';
  previousMode?: 'anchored' | 'generated';
  sourceChunk: string;
}

export interface ClozePuzzle {
  kind: 'cloze';
  id: string;
  spaceId: string;
  items: ClozeItem[];
}

export interface FlashcardItem {
  termId: string;
  front: string;
  back: string;
}

export interface FlashcardsPuzzle {
  kind: 'flashcards';
  id: string;
  spaceId: string;
  items: FlashcardItem[];
}

export type Puzzle = CrosswordPuzzle | ClozePuzzle | FlashcardsPuzzle;

/**
 * Coach hint payload. Promoted out of the previous inline shape on `CoachEvent` so the
 * overlay can style each tier independently. `kind` distinguishes the three tiers from
 * `docs/PLAN.md`: LLM nudge in the notes' register, deterministic structural hint
 * (length + first letter), and definition reveal.
 */
export interface Hint {
  termId: string;
  tier: 1 | 2 | 3;
  kind?: 'nudge' | 'pattern' | 'definition';
  text: string;
}

/**
 * REST + WS message shapes.
 */
export interface HealthResponse {
  ok: true;
  service: 'pachu-backend';
  version: string;
  uptimeMs: number;
  llm: { reachable: boolean; provider: 'ollama'; model: string };
}

/** `POST /notes/ingest` request body. `content` is the raw notes text (UTF-8). */
export interface IngestRequest {
  title: string;
  content: string;
}

/** `POST /notes/ingest` response body. Returns the newly-created `Space`. */
export interface IngestResponse {
  space: Space;
}

/**
 * `POST /spaces/:id/extract` response body.
 *
 * Runs the LLM term extractor against the space's stored raw text, runs the tier-1 span
 * verifier on each candidate, persists the survivors as `Term` rows, and returns the
 * refreshed `Space`. The request has no body — the space id is in the URL, and the
 * extractor's own knobs (model, max terms) live server-side.
 *
 * `rejectedCount` is the number of LLM candidates that failed verification; surfaced
 * for diagnostics during the demo so a judge can see the anti-hallucination contract
 * actually filtering. `acceptedCount === space.summary.termCount` when extraction runs
 * against a fresh space, but diverges if we ever support re-extraction on top of
 * existing terms.
 */
export interface ExtractTermsResponse {
  space: Space;
  acceptedCount: number;
  rejectedCount: number;
}

/** `POST /puzzles/generate` request body. */
export interface GeneratePuzzleRequest {
  kind: PuzzleKind;
  spaceId: string;
  /** Soft target for the number of cards/clues to include. Backend may return fewer. */
  targetCount?: number;
}

/** `POST /puzzles/:id/finish` request body. */
export interface SessionFinishRequest {
  puzzleId: string;
  reviews: Review[];
  /** Timestamp at which puzzle generation completed (used for the `ms` field on Reviews). */
  sessionStartedAt: string;
}

/** `POST /puzzles/:id/finish` response body. */
export interface SessionFinishResponse {
  acceptedCount: number;
  /** ISO timestamp of the next time any term in the space becomes due. */
  nextDueAt?: string;
  /** Refreshed `Space` to save the caller a follow-up `GET /spaces/:id` round-trip. */
  space?: Space;
}

export type CoachEvent =
  | { type: 'hello'; sessionId: string }
  | { type: 'mistake'; termId: string; observation: string }
  | { type: 'hint'; hint: Hint }
  | { type: 'pong' };

export type CoachClientMessage =
  | { type: 'ping' }
  | { type: 'mistake'; termId: string; observation: string }
  | { type: 'hint_request'; termId: string; tier: 1 | 2 | 3 };

/**
 * `/extract` WebSocket — real-time term-extraction progress.
 *
 * Stages, in order:
 *   - `preparing`   : looking up the stored notes
 *   - `calling-model`: the LLM call is in flight; `current` carries the running
 *                      streamed token count (the slow part)
 *   - `verifying`   : span/grounding checks, `current`/`total` populated
 *   - `persisting`  : writing accepted terms
 * Terminates with `done` (refreshed Space + counts) or `error` (HTTP-equivalent
 * status so the client can branch the same way it does on the REST route).
 */
export type ExtractStage =
  | 'preparing'
  | 'calling-model'
  | 'verifying'
  | 'persisting';

export type ExtractClientMessage =
  | { type: 'ping' }
  | { type: 'start'; spaceId: string };

export type ExtractEvent =
  | { type: 'hello' }
  | { type: 'stage'; stage: ExtractStage; current?: number; total?: number }
  | {
      type: 'done';
      space: Space;
      acceptedCount: number;
      rejectedCount: number;
    }
  | { type: 'error'; status: number; message: string }
  | { type: 'pong' };
