/**
 * Cross-cutting types shared between backend and React Native app.
 * Keep this file dependency-free and runtime-free (types only or trivial constants).
 */

export type PuzzleKind = 'crossword' | 'cloze' | 'flashcards';

/**
 * A note source uploaded or pasted by the user.
 */
export interface NotesFile {
  id: string;
  title: string;
  createdAt: string;
  byteLength: number;
}

/**
 * A term extracted from the user's notes. The masked answer in any puzzle is always a verified term.
 *
 * - `sourceSpan` is a literal substring of the source notes (anti-hallucination tier 1).
 * - `styleAnchor` is the original sentence the term appeared in. Every clue/cloze/coach prompt
 *   receives this as a "match this style" reference (source-mimicry register strategy).
 */
export interface Term {
  id: string;
  notesFileId: string;
  term: string;
  definition: string;
  sourceSpan: string;
  styleAnchor: string;
}

/**
 * FSRS-rated review of a single term within a session. 1=Again, 2=Hard, 3=Good, 4=Easy.
 */
export type Rating = 1 | 2 | 3 | 4;

export interface Review {
  termId: string;
  rating: Rating;
  ms: number;
  hintsUsed: number;
}

/**
 * Crossword puzzle payload returned by the backend.
 */
export interface CrosswordEntry {
  term: string;
  clue: string;
  termId: string;
  startX: number;
  startY: number;
  orientation: 'across' | 'down';
}

export interface CrosswordPuzzle {
  kind: 'crossword';
  id: string;
  width: number;
  height: number;
  entries: CrosswordEntry[];
}

/**
 * Cloze puzzle item. `mode` records whether the sentence came from the notes verbatim
 * or was generated by the LLM (with a grounding verifier check).
 */
export interface ClozeItem {
  termId: string;
  sentence: string;
  answer: string;
  mode: 'anchored' | 'generated';
  sourceChunk: string;
}

export interface ClozePuzzle {
  kind: 'cloze';
  id: string;
  items: ClozeItem[];
}

export interface FlashcardItem {
  termId: string;
  front: string;
  back: string;
}

export interface FlashcardsPuzzle {
  kind: 'flashcards';
  id: string;
  items: FlashcardItem[];
}

export type Puzzle = CrosswordPuzzle | ClozePuzzle | FlashcardsPuzzle;

/**
 * REST + WS message shapes.
 */
export interface HealthResponse {
  ok: true;
  service: 'pachu-backend';
  version: string;
  uptimeMs: number;
  llm: { reachable: boolean; provider: 'ollama'; model: string };
}

export type CoachEvent =
  | { type: 'hello'; sessionId: string }
  | { type: 'mistake'; termId: string; observation: string }
  | { type: 'hint'; termId: string; tier: 1 | 2 | 3; text: string }
  | { type: 'pong' };

export type CoachClientMessage =
  | { type: 'ping' }
  | { type: 'mistake'; termId: string; observation: string }
  | { type: 'hint_request'; termId: string; tier: 1 | 2 | 3 };
